Fix custom labels not being displayed
nextcloud/contacts pull request #2064
Opened 2021-02-17 23:26 UTC by Y0hy0h

Should fix #1842.

The `canDisplay` filtering was [introduced almost a year ago](https://github.com/nextcloud/contacts/commit/417448cac5e1ebac691a8fc417a578f45e9bf08e#diff-42f8560182cc1534801c80adee527b8a79c2c55308e110a799c86ccb808cdf39R384). It checks whether the property name is "registered" in [`rfcProps.js`](https://github.com/nextcloud/contacts/blob/master/src/models/rfcProps.js), and if not, it does not pass it along.

The problem is that custom labels are implemented by using two vCard fields with the same, e.g., `group1.X-ABLabel` and `group1.TEL`, where the `.` separates the prefix from the field types. [The sorting function sorts by what is after the `.`](https://github.com/nextcloud/contacts/blob/master/src/components/ContactDetails.vue#L366), since we are not interested in the prefix. By the same logic, we should only check what is after the `.` for whether it is a property we can display.

Unfortunately, I currently don't have the time to figure out how to test this change. But I'm confident enough that this is the fix that I wanted to propose it in the form of a PR.

2021-02-17 23:32 UTC, Y0hy0h commented
Sorry, I had an embarrassing missing paren.

2021-02-17 23:33 UTC, Y0hy0h commented
And now DCO is happy.

2021-02-17 23:36 UTC, Y0hy0h commented
And now I turned of my auto-formatter. Sorry for the noise.

2021-02-18 07:15 UTC, skjnldsv requested changes
Hey, thanks for this!
The fix should go in the canDisplay method.
https://github.com/nextcloud/contacts/blob/5c63289fd7eb7ac5122d1e061ab43a1b89442957/src/components/ContactDetails.vue#L763-L770

Here you drop the normal properties. You need to stay compatible with the non-split properties

2021-02-18 07:18 UTC, skjnldsv approved these changes

2021-02-18 07:19 UTC, skjnldsv commented
Done, I pushed! @Y0hy0h please double check my changes :)

Thanks a lot for narrowing this!

2021-02-18 09:06 UTC, Y0hy0h commented
Yeah, this makes sense! Also great idea to add the comment. 

I'm happy it helped! Thanks for fixing the fix so quickly. 😊

2021-02-18 09:37 UTC, merged

2021-02-18 13:41 UTC, sciurius commented
I can confirm that this solved the problem for me. I have many contacts that have ADR entries similar to

    item0.ADR;TYPE=HOME: ...
    item0.X-ABADRLnl

With the fix the address information is displayed again.

Thanks, Johannes!

2021-02-18 14:57 UTC, skjnldsv commented
I'll release a new version as soon as possible

2023-10-04 11:15 UTC, PHP-Expert commented
Just a short push / comment, that this Topic is still open and can be reproduced when connecting IOS to Nextcloud contacts

2023-10-04 11:27 UTC, ChristophWurst commented
@PHP-Expert file a new bug report please

2023-10-04 12:22 UTC, PHP-Expert commented
https://github.com/nextcloud/contacts/issues/3645