try to fix mobile contacts list
nextcloud/contacts pull request #2382
Opened 2021-07-29 15:57 UTC by szaimen

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-07-29 20:59 UTC, skjnldsv commented on src/components/ContactsList.vue
> +	max-height: calc(100vh - 50px);
https://github.com/nextcloud/server/blob/5fd9ce9e8de61d606cb53eaf24a1c51f2fb2b87a/core/css/css-variables.scss#L59

2021-07-29 20:59 UTC, skjnldsv requested changes
See comment

2021-07-29 21:03 UTC, szaimen commented on src/components/ContactsList.vue
> +	max-height: calc(100vh - 50px);
done

2021-07-29 21:03 UTC, szaimen commented
> See comment

done

2021-07-30 06:16 UTC, skjnldsv approved these changes

2021-07-30 06:16 UTC, skjnldsv commented
Didn't test

2021-07-30 07:47 UTC, szaimen commented
Just tested again and works

2021-07-30 07:47 UTC, merged