fix some settings styling
nextcloud/contacts pull request #2410
Opened 2021-08-26 21:58 UTC by szaimen

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/131045446-34be7d6b-7aa0-441a-a175-fc93b6180332.png) | ![image](https://user-images.githubusercontent.com/42591237/131358374-a0090d11-7432-4ccc-abfe-6f5f086e3c4b.png) |

Signed-off-by: szaimen <szaimen@e.mail.de>

2021-08-30 08:49 UTC, skjnldsv approved these changes

2021-08-30 08:49 UTC, skjnldsv requested changes

2021-08-30 08:49 UTC, skjnldsv commented on src/components/AppNavigation/SettingsSection.vue
> +			<label for="socialSyncToggle" style="white-space: nowrap;">{{ t('contacts', 'Update avatars from social media') }}</label>
Please no inline styling

2021-08-30 14:43 UTC, szaimen commented on src/components/AppNavigation/SettingsSection.vue
> +			<label for="socialSyncToggle" style="white-space: nowrap;">{{ t('contacts', 'Update avatars from social media') }}</label>
reverted this

2021-08-30 14:44 UTC, szaimen commented
> I see. But then I prefer the currently broken version over the new broken version 🙊

I've reverted my changes to this element. Now it will wrap like before.

2021-08-31 07:17 UTC, ChristophWurst approved these changes

2021-08-31 07:18 UTC, merged