Multiple merge delete
nextcloud/contacts pull request #2756
Opened 2022-05-24 10:19 UTC by MrPompom

**commits to add features linked to :https://github.com/nextcloud/contacts/issues/70#issue-197512830 and https://github.com/nextcloud/contacts/issues/277#issue-248344665**

## How it works :
When the mouse is over a contact, the avatar changes to a checkbox.
The checkbox can be checked, when only 1 checkbox is selected, the delete button appears, when it's 2 or more it's a menu with the delete and merge button.
 
![image](https://user-images.githubusercontent.com/62659819/170001194-fe88395f-001d-4cbc-b2b6-cb163a30b842.png)

### Delete :

When the delete button is clicked, all the selected contacts are deleted
![image](https://user-images.githubusercontent.com/62659819/170005285-3b3726bf-d8d7-403c-9190-ae817024f4d8.png)

### Merge :

When the merge button is clicked, it will merge all the selected contacts into the first selected contact
![image](https://user-images.githubusercontent.com/62659819/170005985-31a21b43-8590-428a-9a10-16253ba7c7c3.png)

The value except *uid*, *version*, *fn*, *prodid*, *gender*, *rev*  will be added into the first selected contact

The value who already exist and default value will not be added
![image](https://user-images.githubusercontent.com/62659819/170008545-0926a0e8-dd9c-4feb-b909-982c482395c3.png)

2022-10-11 10:12 UTC, szaimen commented
I just rebased this. Hopefully I didn't break anything while doing so.

2022-10-17 17:50 UTC, ChristophWurst requested changes
A little but important detail missing is handling of address book relations. IMO if all selected contacts belong to the same AB, the merging is OK to do, but across ABs (especially when they are shared) you have to either forbid the operation or ask the user what destination AB they want the merged contact to be written to.

I also don't see any handling of ACLs. It's possible that some ABs are read-only. Then they should probably be ignored for merging as you can neither merge into those contacts nor delete the contact after merging into another AB.

2023-01-17 10:39 UTC, ChristophWurst commented
@MrPompom please have a look at https://github.com/nextcloud/contacts/pull/2756#pullrequestreview-1144582880. Would that be something you could address? Cheers

2024-02-16 23:14 UTC, melroy89 commented
I really would like to have multi contact selection for batch deletion, that would be a very very welcome feature. Without the need of installing Thunderbird.

2025-08-21 07:52 UTC, st3iny commented
Has been implemented in https://github.com/nextcloud/contacts/pull/4521 and

2025-08-21 07:52 UTC, closed without merging