Issue #2284
nextcloud/contacts pull request #3106
Opened 2022-11-18 10:03 UTC by aryatalathi

changed "There is no member in this circle" to "You currently have no access to the memberlist".

2022-11-18 10:09 UTC, ChristophWurst requested changes
Please undo/revert the changes in `l10n/`. The translations are handled by Transifex via an automation. Those files are not touched by us developers :)

2022-11-19 07:52 UTC, aryatalathi commented
> Please undo/revert the changes in `l10n/`. The translations are handled by Transifex via an automation. Those files are not touched by us developers :)

Okay. I have reverted the changes in `l 10n/`. Kindly check. Thank you!

2022-12-12 03:05 UTC, aryatalathi commented on src/components/AppNavigation/ContactsSettings.vue
> +	border-color: black !important;
Requesting to review and merge. 
The required changes are made.
Thank you!

2022-12-13 05:03 UTC, aryatalathi commented
Respected sir,
I have made only required changes and have reverted the unnecessary
commits. Kindly check so the PR can get merged. Thank you.

2022-12-13 07:31 UTC, ChristophWurst commented
Please see https://github.com/nextcloud/contacts/pull/3106/files. The requested revert has not been done.

2022-12-13 08:38 UTC, aryatalathi commented
> Please see https://github.com/nextcloud/contacts/pull/3106/files. The requested revert has not been done.

I have tried to revert it, but its not reflecting here. May I push the required changes on new branch and create a new pull request?

2022-12-13 08:44 UTC, ChristophWurst commented
Sure

2022-12-13 08:44 UTC, closed without merging

2022-12-13 09:05 UTC, aryatalathi commented
Kindly check #3133  <https://github.com/nextcloud/contacts/pull/3133>.

On Tue, Dec 13, 2022 at 2:14 PM Christoph Wurst ***@***.***>
wrote:

> Sure
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nextcloud/contacts/pull/3106#issuecomment-1347939433>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANGUR2LGVOPQQMYSEX4PBD3WNAZOXANCNFSM6AAAAAASEKAV6Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>