#3067 border-color
nextcloud/contacts pull request #3113
Opened 2022-11-23 13:55 UTC by aryatalathi

2022-11-23 14:04 UTC, ChristophWurst commented
Thanks a lot for the contribution @aryatalathi! For design changes it's recommended to post a before and after screenshot that shows the UI before your change and after. Could you add this here as a comment? Thanks!

2022-12-15 15:14 UTC, ChristophWurst commented
Hey @aryatalathi,

Could you please post a *before* and *after* screenshot to demo your changes?

Cheers

2023-04-20 08:31 UTC, ChristophWurst commented
Hey @aryatalathi,

Could you please post a before and after screenshot to demo your changes?

Cheers

2023-04-20 08:33 UTC, ChristophWurst requested changes

2023-04-20 08:33 UTC, ChristophWurst commented on src/components/AppNavigation/ContactsSettings.vue
> +	border-color: black !important;
I'm convinced this should use a css var, not a hard-coded value. The black border will be problematic with a bright theme.

2024-11-01 13:06 UTC, SebastianKrupinski commented
This issue is no longer applicable.

2024-11-01 13:06 UTC, closed without merging