More appropriate circle section wording
nextcloud/contacts pull request #3441
Opened 2023-06-06 07:52 UTC by Jerome-Herbinet

"user" groups instead of "contact" groups because here are listed user groups and not contact groups (if I'm not mistaking).

![2023-06-06_09-45](https://github.com/nextcloud/contacts/assets/33763786/275c47dd-6aab-462b-aeb5-63a3c567f211)

2023-06-08 11:23 UTC, jancborchardt requested changes
Indeed it does not take "Contact groups" here but just the regular groups from the accounts. It should be simply called "Groups", as we call it like that elsewhere too.

It also needs to be adjusted in the "Add members" modal for the subheading, if you'd like to do that as well @Jerome-Herbinet :) 
![image](https://github.com/nextcloud/contacts/assets/925062/3e77b7cc-fef4-49d2-a41e-e5441bbcee40)

2023-06-08 14:14 UTC, ArtificialOwl commented
> You're right @Jerome-Herbinet. Actually I'm a bit confused since I thought Circles allows you to add both "account groups" and "contact groups" to a circle. The omission of "contact groups" is a bit strange since contacts individually can be added.
> 
> @ArtificialOwl any specific reason here?

It has never been officially requested :-)

2023-06-22 11:45 UTC, Jerome-Herbinet commented
Hello @jancborchardt @ArtificialOwl, 
What's the roadmap about this PR and/or the circle enhancement to take in account contact groups ?
Cheers,
Jerome

2024-04-19 09:35 UTC, Jerome-Herbinet commented
> Hello @jancborchardt @ArtificialOwl, What's the roadmap about this PR and/or the circle enhancement to take in account contact groups ? Cheers, Jerome

@jancborchardt @ArtificialOwl , any news ?

2024-08-20 10:02 UTC, jancborchardt reviewed
@Jerome-Herbinet since an implementation of being able to add contact groups as well is not currently on the roadmap, I’d suggest to go with the simple wording change for now. And I would say that should simply be "Groups".

> Elsewhere in Nextcloud, when there can be no confusion, we can make do with "Groups" without any problem, but not in this specific case, which I think is an exception.

I think it is better to be consistent – otherwise we don’t have 2 terms, but instead 3.

2024-08-20 11:33 UTC, Jerome-Herbinet commented
OK @jancborchardt ; I'll close my PR because @mejo- exactly recently did what you suggest : https://github.com/nextcloud/contacts/pull/4076

2024-08-20 11:33 UTC, closed without merging

2024-08-20 14:28 UTC, jancborchardt commented
Ah cool, well thank you both @Jerome-Herbinet @mejo-! :)