Fix handling group update
nextcloud/contacts pull request #3452
Opened 2023-06-12 10:59 UTC by hamza221

fix  #3415

The state was changing on local value update.
open for alternative, cleaner?  solution ideas 🧐

2023-06-12 11:44 UTC, st3iny reviewed
Some minor feedback. There are more cosmetic issues that should be automatically fixed by the linter (`npm run eslint:fix`).

I'm currently testing the PR.

2023-06-12 11:44 UTC, st3iny commented on src/components/Properties/PropertyGroups.vue
> +					:taggable:="true"
```suggestion
					:taggable="true"
```

2023-06-12 11:44 UTC, st3iny commented on src/components/Properties/PropertyGroups.vue
>  		 * @param {string} groupName the group name
```suggestion
		 * Send update event to parent
```

2023-06-12 11:44 UTC, st3iny commented on src/components/Properties/PropertyGroups.vue
> +			this.$emit('update',this.localValue)
```suggestion
		updateValue() {
			this.$emit('update:value', this.localValue)
```

2023-06-12 11:44 UTC, st3iny commented on src/store/groups.js
> +
```suggestion
```

2023-06-12 11:44 UTC, st3iny commented on src/store/groups.js
> +	updateContactGroup(context, { groupNames, contact }){
```suggestion
	updateContactGroups(context, { groupNames, contact }) {
```

2023-06-12 11:44 UTC, st3iny commented on src/components/ContactDetails.vue
> +					@update="updateGroups"/>
```suggestion
					@update:value="updateGroups"/>
```

2023-06-12 11:44 UTC, st3iny commented on src/components/ContactDetails.vue
> +				await this.$store.dispatch('updateContactGroup', {
```suggestion
				await this.$store.dispatch('updateContactGroups', {
```

2023-06-12 11:47 UTC, st3iny commented on src/components/Properties/PropertyGroups.vue
> +					:limit="3"
Why limit to 3? This means that a user is not able to see all groups in the dropdown.

2023-06-12 11:50 UTC, st3iny reviewed
I tested the repro from #3415 and the PR fixes the issue.

2023-06-12 12:17 UTC, st3iny commented
Does it fix #3415?

2023-06-12 12:22 UTC, hamza221 commented
> Does it fix #3415?

I was not able to reproduce the bug, So I'm not sure

2023-06-13 07:27 UTC, st3iny commented on src/components/Properties/PropertyGroups.vue
> +					:limit="3"
Which comment? IMO, the limit should be removed.

2023-06-13 07:28 UTC, st3iny requested changes
Tested and works. Please address https://github.com/nextcloud/contacts/pull/3452#discussion_r1227656573.

2023-06-20 12:06 UTC, JohannesGGE approved these changes

2023-06-22 07:35 UTC, ChristophWurst commented
Fixup check fails because of https://github.com/nextcloud/contacts/issues/3476

2023-06-22 07:35 UTC, merged