Enh/Enhance group information display
nextcloud/contacts pull request #3752
Opened 2023-12-20 18:58 UTC by GVodyanov

Fix https://github.com/nextcloud/contacts/issues/3706

| Before | After |
| - | - |
| ![image](https://github.com/nextcloud/contacts/assets/76647797/8d41bb03-87e4-481d-a574-0fa3b1b1efbd) | ![image](https://github.com/nextcloud/contacts/assets/76647797/29129951-d635-4151-b252-58ac50a417ff) |

2023-12-21 16:47 UTC, hamza221 requested changes

2023-12-21 16:47 UTC, hamza221 commented on src/components/Properties/PropertyGroups.vue
> +					<div class="group__list">
```suggestion
					<div v-else class="group__list">
```
so we don't get an empty div in the dom

2024-04-02 08:19 UTC, hamza221 commented
@GVodyanov can you please check failing CI ^^

2024-04-11 10:06 UTC, hamza221 commented
@GVodyanov friendly ping

2024-04-11 16:39 UTC, GVodyanov commented
Sorry here I am, btw during testing I found this https://github.com/nextcloud/contacts/issues/3880, looks pretty bad @hamza221

2024-04-15 16:22 UTC, hamza221 approved these changes

2024-04-15 16:23 UTC, hamza221 commented
@ChristophWurst  Is this the desired UI?

2024-04-15 16:51 UTC, ChristophWurst commented
Seems find if I look at the screenshots of https://github.com/nextcloud/contacts/issues/3706

2024-04-15 16:53 UTC, merged